#!/usr/bin/env python3
"""Embed a binary file as a 64-byte-aligned C++ array.  Usage: bin2cpp.py IN.bin OUT.cpp"""
import sys

src, dst = sys.argv[1], sys.argv[2]
data = open(src, "rb").read()
with open(dst, "w") as f:
    f.write(f"// Generated by tools/bin2cpp.py from {src}. Do not edit.\n#include <cstddef>\n")
    f.write("extern const unsigned char NNUE_DATA[];\nextern const size_t NNUE_DATA_SIZE;\n")
    f.write("alignas(64) const unsigned char NNUE_DATA[] = {\n")
    for i in range(0, len(data), 32):
        f.write(",".join(str(b) for b in data[i:i + 32]) + ",\n")
    f.write(f"}};\nconst size_t NNUE_DATA_SIZE = {len(data)};\n")
